### ISSUE TITLE
This looks interesting. What is it?

### ISSUE THREAD

**Issue by VIVelev** [umnikos/atomic-exchange-interpreter#1]
Hey Alex,

This looks pretty interesting, what is it?
I suspect it's some kind of a minimalistic framework of computation?

Would be awesome if you could share some references, couldn't find any myself.

Cheers,
Victor

**Comment by umnikos** [comment]
I added the WIP docs to the repo. I hoped I'd get to rewrite the thing before uploading it but I guess not, lol

**Comment by VIVelev** [comment]
Um, shouldn't substraction actually be:
```
    _
    U
    |
    \----------------\
       \w/ /--\      |
    >>-----|   \/\/-<--\
           |   /  \    |
           \--<w  b>---/
           /-1\ \  /
                /\/
               |
       /-o-----/
       | 
       U
```

Instead of the one in the docs, am I getting something wrong?
Sorry to bother you, let me know if I am annoying!

**Comment by umnikos** [comment]
Something like this would work if atoms were allowed to hold negative integers. The way the subtraction operator in the docs works is by incrementing the smaller number with 1s until it reaches the big number (for 5-2, {2} becomes {2,1,1,1}) and then discards the number we were subtracting ({2,1,1,1} becomes {1,1,1}) before summing the increments into a result.

**Comment by VIVelev** [comment]
Oh, that makes total sense, thanks! Is there a reason atoms can't hold negatives? Do you plan to represent them in any way?

**Comment by umnikos** [comment]
I think the language would still be turing complete even with negative values so I don't think there is a real reason apart from simplicity. One of the ideas I am working on is replacing the atoms entirely for some other data structure or expanding what they can hold beyond the realm of simple integers but nothing has caught my eye yet.

**Comment by VIVelev** [comment]
You should definitely checkout Lambda Calculus - it's a nice mathematical formalism and may give you some cool ideas for language design. I myself am currently delving into Lambda Calculus and LISP and is awesome! So, if you want to discuss with someone - I am open!

**Comment by umnikos** [comment]
If you liked both of those consider checking out Haskell! Lazy evaluation + pure functional programming is an amazingly great combination that never ceases to be fun. (lisp is neither pure nor lazy, if you're wondering)

**Comment by VIVelev** [comment]
Yeah, I actually first started looking into Haskell with the intention of learning functional programming, then got dragged into Lambda Calculus and now LISP, but I will definitely come back to Haskell some time.

**Comment by umnikos** [comment]
As far as I know the main reason one would use lisp today is for the metaprogramming capabilities. I'd like to learn enough lisp to get to that but never found the time or reason to...

**Comment by VIVelev** [comment]
Imo it's much more then metaprogramming (although this is a huge part). LISP also has the idea of closures (not the function ones, but data related ones), also the syntax is so nice ones you get used to it, it's super consistent. And in general it feels like you can keep all the details of the language in your head at all times (largely thanks to Lambda Calc), which is a huge benefit for me.

Btw, do you want to move further conversation to discord?

**Comment by umnikos** [comment]
Sure, my discord is listed on my github profile
